name: Deploy

on:
  push:
    branches:
      - develop
  schedule:
    - cron: '0 9 * * *'
    - cron: '0 3 * * *'

env:
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
          registry-url: 'https://registry.npmjs.org'
      - name: Install packages
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Define deploy_id
        run: |
          echo "deploy_id=${{ github.job }}-${{ github.run_id }}-${{ github.run_attempt }}" >> $GITHUB_ENV
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME_STG }}
          role-session-name: GitHubActions-${{ env.deploy_id }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: copy files to s3 bucket
        run: |
          aws s3 sync --delete out s3://${{ secrets.BUCKET_NAME_STG }}/experimental/
      - name: invalidate cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DIST_ID_STG }} --paths "/experimental/*"
